import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';

const temp = await mkdtemp(path.join(tmpdir(), 'standalone-aiocr-'));
process.env.AIOCR_DATA_DIR = temp;
process.env.AIOCR_BACKUP_DIR = path.join(temp, 'backups');
process.env.AIOCR_PORT = '0';
process.env.AIOCR_USERNAME = 'test-admin';
process.env.AIOCR_PASSWORD = 'test-password';
process.env.AIOCR_FACILITY_ID = 'facility-a';
process.env.AIOCR_ENCRYPTION_KEY = 'test-only-encryption-key-32-characters-minimum';
process.env.AIOCR_SKIP_LOCAL_ENV = '1';
const { server } = await import('../server.mjs');
await new Promise(resolve => server.listening ? resolve() : server.once('listening', resolve));
const address = server.address();
const base = `http://127.0.0.1:${address.port}`;
const auth = `Basic ${Buffer.from('test-admin:test-password').toString('base64')}`;
const health = await fetch(`${base}/api/health`).then(r => r.json());
assert.equal(health.ok, true);
assert.equal(health.imageDetail, 'original');
assert.equal(health.reasoningEffort, 'low');
assert.equal(health.retryReasoningEffort, 'high');
const captureHtml = await readFile(new URL('../public/index.html', import.meta.url), 'utf8');
assert.match(captureHtml, /id="imageInput"[^>]*accept="image\/\*,application\/pdf,\.pdf"[^>]*multiple/);
assert.doesNotMatch(captureHtml, /id="imageInput"[^>]*capture=/);
assert.match(captureHtml, /id="patientSheetTimeline"/);
assert.match(captureHtml, /患者リハビリ履歴/);
assert.match(captureHtml, /id="evaluationDateOverride"/);
assert.match(captureHtml, /id="therapistSearch"/);
assert.match(captureHtml, /id="therapistSearchList"/);
assert.match(captureHtml, /評価実施日（過去の評価登録可能）/);
assert.match(captureHtml, /id="refreshPatientSheets"/);
assert.match(captureHtml, /id="deleteAllHistory"/);
const captureApp = await readFile(new URL('../public/app.js', import.meta.url), 'utf8');
const cameraApp = await readFile(new URL('../public/camera-capture.js', import.meta.url), 'utf8');
const cameraCss = await readFile(new URL('../public/camera-capture.css', import.meta.url), 'utf8');
const captureCss = await readFile(new URL('../public/capture-layout.css', import.meta.url), 'utf8');
const patientTimelineCss = await readFile(new URL('../public/patient-timeline.css', import.meta.url), 'utf8');
const serverSource = await readFile(new URL('../server.mjs', import.meta.url), 'utf8');
assert.match(serverSource, /reasoning:\s*\{\s*effort:\s*reasoningEffort\s*\}/);
assert.match(serverSource, /buildRoutedOcrPrompt/);
assert.match(serverSource, /\{\s*1:\s*32,\s*2:\s*29,\s*3:\s*9/);
assert.match(serverSource, /buildBitPage1Prompt/);
assert.match(serverSource, /buildTargetedRetryPrompt/);
assert.match(serverSource, /prompt_cache_key/);
assert.match(serverSource, /for \(let attempt = 0; attempt < 3; attempt\+\+\)/);
assert.match(serverSource, /\[408, 409, 429\]/);
assert.match(serverSource, /An error occurred while processing/);
assert.match(serverSource, /testType === 'BBS' && filledFieldCount\(ocr\.result\) < 14/);
assert.match(serverSource, /testType === 'STEF' && filledStefTimeCount\(ocr\.result\) < 20/);
assert.match(serverSource, /testType === 'FMA_1' && filledFieldCount\(ocr\.result\) < 33/);
assert.match(captureHtml, /id="cameraSheetOverlay"/);
assert.match(cameraApp, /\/api\/detect-sheet/);
assert.match(cameraApp, /評価シートを判定中/);
assert.match(cameraApp, /showSheetOverlay\(result\.displayName,\s*'recognized'\)/);
assert.doesNotMatch(cameraApp, /認識した評価シート：/);
assert.match(cameraApp, /function liveFrameDataUrl\(\)/);
assert.match(cameraApp, /function startLiveDetection\(\)/);
assert.match(cameraApp, /scheduleLiveDetection\(2000\)/);
assert.match(cameraApp, /detectEvaluationSheet\(imageDataUrl,\s*\{\s*live:\s*true\s*\}\)/);
assert.match(cameraApp, /stopLiveDetection\(\);[\s\S]*?canvas\.width/);
assert.match(cameraApp, /await video\.play\(\);\s*startLiveDetection\(\)/);
assert.match(cameraCss, /\.camera-sheet-overlay/);
assert.match(cameraCss, /data-state="recognized"/);
assert.match(cameraCss, /\.camera-sheet-overlay\s*\{[\s\S]*?top:\s*-58px/);
assert.match(captureHtml, /id="cameraSheetOverlay"[\s\S]*?>シート判定<\/div>/);
assert.doesNotMatch(captureHtml, /A4用紙を撮影|A4用紙を枠内に合わせてください/);
assert.doesNotMatch(captureHtml, /camera-guide-label/);
assert.match(captureHtml, /class="camera-actions">\s*<button id="closeCameraButton"[\s\S]*?<button id="shootCameraButton"/);
assert.doesNotMatch(captureHtml, /camera-header[\s\S]*?id="closeCameraButton"[\s\S]*?<\/header>/);
assert.match(cameraCss, /\.camera-actions \.camera-close-button/);
assert.match(cameraCss, /\.camera-actions\s*\{\s*position:\s*relative/);
assert.match(cameraCss, /\.camera-actions \.camera-close-button\s*\{[\s\S]*?position:\s*absolute;[\s\S]*?left:\s*18px;[\s\S]*?top:\s*50%/);
assert.match(captureHtml, /id="cameraCaptureSlots"/);
assert.match(captureHtml, /id="cameraCaptureCount"/);
assert.match(captureHtml, /id="finishCameraButton"/);
assert.match(captureHtml, /id="shootCameraButton"[\s\S]*?id="finishCameraButton"[\s\S]*?>画像を使用<\/button>/);
assert.match(cameraCss, /\.camera-finish-button\s*\{[\s\S]*?position:\s*absolute;[\s\S]*?right:\s*18px/);
assert.match(cameraApp, /const maxCameraCaptures = 13/);
assert.match(cameraApp, /Array\.from\(\{ length: maxCameraCaptures \}/);
assert.match(cameraApp, /capturedSheets\.filter\(Boolean\)\.forEach\(item => transfer\.items\.add\(item\.file\)\)/);
assert.match(cameraCss, /\.camera-capture-slots/);
assert.match(cameraCss, /display:\s*flex/);
assert.match(cameraCss, /flex-wrap:\s*nowrap/);
assert.match(cameraCss, /overflow-x:\s*scroll/);
assert.match(cameraCss, /touch-action:\s*pan-x/);
assert.match(cameraCss, /flex:\s*0 0 48px/);
assert.doesNotMatch(cameraCss, /aspect-ratio:\s*297\s*\/\s*210/);
assert.doesNotMatch(captureHtml, /id="retakeCameraButton"/);
assert.doesNotMatch(captureHtml, /id="useCameraButton"/);
assert.match(captureHtml, /id="cameraPreviewDialog"/);
assert.match(cameraApp, /activeCaptureIndex = Number\(button\.dataset\.selectCapture\)/);
assert.match(cameraApp, /previewDialog\.showModal\(\)/);
assert.match(cameraApp, /capturedSheets\[activeCaptureIndex\] = \{ file, url: URL\.createObjectURL\(blob\) \}/);
assert.match(cameraCss, /\.camera-capture-slot\.active/);
assert.match(cameraApp, /const coverScale = Math\.max/);
assert.match(cameraApp, /const guideRect = cameraGuide\.getBoundingClientRect\(\)/);
assert.match(cameraApp, /context\.drawImage\(\s*video,\s*sourceX,\s*sourceY,\s*sourceWidth,\s*sourceHeight/);
assert.match(serverSource, /async function detectEvaluationSheet/);
assert.match(serverSource, /rehainfo-sheet-detection-v1/);
assert.match(serverSource, /url\.pathname === '\/api\/detect-sheet'/);
assert.match(serverSource, /SLTA_ALL:\s*12/);
assert.match(serverSource, /BIT:\s*7/);
assert.match(serverSource, /CAT_R_ALL:\s*5/);
assert.match(serverSource, /WAIS_IV_ALL:\s*13/);
assert.match(serverSource, /WMSR_ALL:\s*9/);
assert.match(serverSource, /設問番号、採点番号、患者の手書き数字をページ番号として扱わない/);
assert.match(serverSource, /rawPage <= maxPage/);
assert.match(serverSource, /function validateDetectedSheetSet/);
assert.match(serverSource, /同じ用紙を重複して撮影しています/);
assert.match(serverSource, /不足している用紙があります/);
assert.match(serverSource, /用紙の順番が正しくありません/);
assert.match(serverSource, /url\.pathname === '\/api\/validate-sheet-set'/);
assert.doesNotMatch(cameraApp, /await validateCapturedSheetSet/);
assert.match(cameraApp, /imageInput\.dispatchEvent\(new Event\('change'/);
assert.match(captureApp, /validateOcrSheetSet/);
assert.match(captureApp, /backgroundSheetCheckToken/);
assert.match(captureApp, /バックグラウンドで評価用紙を確認しています/);
assert.match(captureApp, /function cancelBackgroundSheetCheck/);
assert.match(captureApp, /backgroundSheetCheckController\?\.abort\(\)/);
assert.match(captureApp, /startOcrWithPriority/);
assert.match(captureApp, /correctImagesWithPriority/);
const adminApp = await readFile(new URL('../public/admin.js', import.meta.url), 'utf8');
assert.match(adminApp, /hospitals=\[hospital,\.\.\.hospitals\.filter/);
assert.match(adminApp, /renderHospitals\(\);event\.currentTarget\.reset/);
assert.match(adminApp, /data-edit-hospital=/);
assert.match(adminApp, /method:'PUT'/);
assert.match(captureApp, /resizeLongEdge\(dataUrl,maxLongEdge=2048\)/);
assert.match(captureApp, /correctFullEvaluationSheet\(original\)/);
assert.match(captureApp, /removeDocumentShadow\(dataUrl\)/);
assert.match(captureApp, /alignTableForHumanViewing\(shadowRemoved\)/);
assert.match(captureApp, /state\.imageDataUrls=optimized\.map\(item=>item\.imageDataUrl\)/);
assert.match(captureApp, /Math\.min\(4,count\)/);
assert.match(captureApp, /fileName:item\.fileName,pageNumber:item\.pageNumber/);
assert.match(captureApp, /function shortItemText\(value\)/);
assert.match(captureApp, /function visibleResultFields\(result\)/);
assert.match(captureApp, /bitPage2=.*BIT_2_/);
assert.match(captureApp, /chars\.length>16/);
assert.match(captureApp, /itemTextMarkup\(field\.label\)/);
assert.match(captureApp, /const bitPage1=result\?\.testType==='BIT'.*BIT_\\d\+_/);
assert.match(captureApp, /bit-page1-min/);
assert.match(captureApp, /bitPageNumber===1\?\.15\+anchorY\*\.88:anchorY/);
assert.match(captureApp, /if\(bitPage1\)\{\s*return fields\.map/);
assert.match(captureApp, /ocr-value anchored plain/);
assert.match(captureApp, /landscape-overlay/);
assert.match(captureApp, /const bitPageNumber=Number/);
assert.match(captureCss, /\.ocr-value\.bit-page1-min\{min-width:0;padding:1px 5px;transform:translate\(-50%,-50%\);font-size:12px/);
assert.match(captureApp, /function positionBitOverlays\(overlay\)/);
assert.match(captureApp, /translateY\(\$\{boxHeight\+3\}px\)/);
assert.match(captureApp, /class="first-result-row"/);
assert.match(captureApp, /optimizedValueControl\(field,'batch-field-value'\)/);
assert.doesNotMatch(captureApp, /first-result-table/);
assert.match(captureApp, /pdfjsLib\.getDocument/);
assert.match(captureApp, /function renderPatientSheetTimeline\(\)/);
assert.match(captureApp, /function renderClinicalFlow\(patientId\)/);
assert.match(captureApp, /function clinicalEvaluationRuns\(jobs\)/);
assert.match(captureApp, /ページ・1回の評価/);
assert.match(captureApp, /function clinicalEvaluationDate\(job\)/);
assert.match(captureApp, /評価日不明/);
assert.match(captureApp, /evaluationDateOverride/);
assert.match(captureApp, /therapistName=selectedTherapistName\(\)/);
assert.match(captureApp, /evaluationDateOverride'\)\.value=todayValue\(\)/);
assert.match(serverSource, /jobEvaluationDate/);
assert.match(serverSource, /evaluationDateOverride/);
assert.match(captureApp, /\/api\/rehab-records/);
assert.doesNotMatch(captureApp, /id="patientClinicalFlow"/);
assert.doesNotMatch(captureApp, /今回の記録を追加|rehabRecordForm/);
assert.match(serverSource, /rehabRecords/);
assert.match(serverSource, /pre-rehab-summary/);
assert.doesNotMatch(captureApp, /THERAPIST_LEVELS|therapistFeatures|療法士区分/);
assert.match(serverSource, /therapistName/);
assert.match(captureApp, /state\.selectedPatientTimelineId=ocrPatientId/);
assert.match(captureApp, /患者欄にも追加しました/);
assert.match(captureApp, /careStageLabel/);
assert.match(captureApp, /data-discharge-job/);
assert.match(captureApp, /data-undo-discharge-job/);
assert.match(patientTimelineCss, /\.patient-sheet-card\s*\{[\s\S]*?flex-direction:\s*column;[\s\S]*?min-height:\s*350px/);
assert.match(patientTimelineCss, /\.discharge-button\s*\{[\s\S]*?margin:\s*12px 10px 14px/);
assert.match(captureApp, /data-delete-job/);
assert.match(serverSource, /deletedId/);
assert.match(captureApp, /途中経過に戻す/);
assert.match(captureApp, /summaryDischarge/);
assert.doesNotMatch(captureApp, /id="summaryDischarge"/);
assert.match(captureApp, /summaryUndoDischarge/);
assert.match(captureApp, /switchSummaryCareStage/);
assert.match(captureApp, /alreadyDischarged/);
assert.match(captureApp, /dischargeWarningsShown/);
assert.match(serverSource, /hasExistingDischarge/);
assert.match(captureApp, /id="familySummary"/);
assert.match(captureApp, /id="patientSummary"/);
assert.match(serverSource, /familySummary/);
assert.match(serverSource, /patientSummary/);
assert.match(captureApp, /stage-history-row/);
assert.match(captureApp, /評価用紙/);
assert.match(captureApp, /id="rehabSummary"/);
assert.match(captureApp, /initial-summary/);
assert.match(captureApp, /id="generateInitialSummary"/);
assert.match(captureApp, /サマリ生成/);
assert.match(captureApp, /id="progressSummary"/);
assert.match(captureApp, /generateProgressSummary/);
assert.match(captureApp, /id="dischargeSummary"/);
assert.match(captureApp, /generateDischargeSummary/);
assert.match(serverSource, /initial-summary/);
assert.match(serverSource, /rehabSummary/);
assert.match(serverSource, /generateRehabSummary/);
assert.match(serverSource, /generateProgressSummary/);
assert.match(serverSource, /previousSameSheetJob/);
assert.match(serverSource, /generateDischargeSummary/);
assert.match(serverSource, /undoDischargeMatch/);
assert.match(serverSource, /job\.careStage = 'FOLLOW_UP'/);
assert.match(serverSource, /assessmentGroupId/);
assert.match(serverSource, /rebuildAssessmentGroups/);
assert.match(serverSource, /safeText\(job\.therapistName\)\.toLowerCase\(\)/);
assert.match(serverSource, /const assessmentSet = expectedPageCount/);
assert.match(serverSource, /missingPages/);
assert.match(captureApp, /不足：/);
assert.match(captureApp, /全ページ確認済み/);
assert.match(captureApp, /初診サマリ/);
assert.match(captureApp, /全ページのOCR結果/);
assert.match(captureApp, /batch-field-value/);
assert.match(captureApp, /修正内容を保存/);
assert.match(captureApp, /const columns=/);
assert.match(captureApp, /sideCandidates/);
assert.match(captureApp, /class="ocr-value\$\{dense/);
assert.match(captureApp, /collisions\*10000/);
assert.match(serverSource, /SLTA_/);
assert.match(serverSource, /SLTA_.*TEXT.*filter|filter.*SLTA_.*TEXT/s);
assert.match(captureApp, /evaluationName.*SLTA/);
assert.match(captureApp, /初診サマリ/);
assert.match(captureApp, /method:'DELETE'/);
assert.match(captureApp, /OCR用に長辺2400px以下へ最適化済み/);
assert.match(captureApp, /const median=channel=>/);
assert.match(captureApp, /const sustainedBounds=/);
assert.match(captureHtml, /id="batchComparisons"/);
assert.match(captureApp, /function renderBatchComparisons\(\)/);
assert.match(captureApp, /state\.jobs\.slice\(0,20\)/);
assert.match(captureApp, /showAllHistory/);
assert.match(captureApp, /20件表示に戻す/);
assert.match(captureApp, /OCR結果（テキスト）/);
assert.match(captureApp, /String\(field\.value\?\?''\)\.trim\(\)!==''/);
assert.match(captureApp, /_TEXT_/);
assert.match(captureApp, /function alignResultOverlays\(\)/);
assert.match(captureApp, /class="field-label-text"/);
assert.doesNotMatch(captureApp, /class="field-label"/);
assert.match(captureApp, /style="left:\$\{x\}%;top:\$\{y\}%"/);
const denied = await fetch(`${base}/api/patients`);
assert.equal(denied.status, 401);
const loginResponse = await fetch(`${base}/api/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username: 'test-admin', password: 'test-password' }) });
assert.equal(loginResponse.status, 200);
const loginResult = await loginResponse.json();
assert.equal(loginResult.role, 'ADMIN');
assert.equal(loginResult.redirect, '/admin.html');
const sessionCookie = loginResponse.headers.get('set-cookie').split(';')[0];
const sessionPatientsResponse = await fetch(`${base}/api/patients`, { headers: { Cookie: sessionCookie } });
assert.equal(sessionPatientsResponse.status, 200);
const adminPageResponse = await fetch(`${base}/admin.html`, { headers: { Cookie: sessionCookie } });
assert.equal(adminPageResponse.status, 200);
const hospitalCreateResponse = await fetch(`${base}/api/admin/hospitals`, { method: 'POST', headers: { 'Content-Type': 'application/json', Cookie: sessionCookie }, body: JSON.stringify({ name: 'テスト病院', loginName: 'hospital-test', password: 'hospital-password' }) });
assert.equal(hospitalCreateResponse.status, 201);
const hospitalAccount = await hospitalCreateResponse.json();
assert.equal(hospitalAccount.name, 'テスト病院');
assert.equal(hospitalAccount.passwordHash, undefined);
const hospitalLoginResponse = await fetch(`${base}/api/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username: 'hospital-test', password: 'hospital-password' }) });
assert.equal(hospitalLoginResponse.status, 200);
const hospitalLoginResult = await hospitalLoginResponse.json();
assert.equal(hospitalLoginResult.role, 'HOSPITAL');
assert.equal(hospitalLoginResult.redirect, '/');
const hospitalCookie = hospitalLoginResponse.headers.get('set-cookie').split(';')[0];
const hospitalAdminDenied = await fetch(`${base}/api/admin/hospitals`, { headers: { Cookie: hospitalCookie } });
assert.equal(hospitalAdminDenied.status, 403);
const hospitalAdminPageDenied = await fetch(`${base}/admin.html`, { headers: { Cookie: hospitalCookie } });
assert.equal(hospitalAdminPageDenied.status, 403);
const hospitalUpdateResponse = await fetch(`${base}/api/admin/hospitals/${hospitalAccount.id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json', Cookie: sessionCookie }, body: JSON.stringify({ name: '更新テスト病院', loginName: 'hospital-updated', password: 'updated-password' }) });
assert.equal(hospitalUpdateResponse.status, 200);
const updatedHospitalAccount = await hospitalUpdateResponse.json();
assert.equal(updatedHospitalAccount.name, '更新テスト病院');
assert.equal(updatedHospitalAccount.loginName, 'hospital-updated');
assert.equal(updatedHospitalAccount.passwordHash, undefined);
const invalidatedHospitalSession = await fetch(`${base}/api/patients`, { headers: { Cookie: hospitalCookie } });
assert.equal(invalidatedHospitalSession.status, 401);
const oldHospitalLogin = await fetch(`${base}/api/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username: 'hospital-test', password: 'hospital-password' }) });
assert.equal(oldHospitalLogin.status, 401);
const updatedHospitalLogin = await fetch(`${base}/api/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username: 'hospital-updated', password: 'updated-password' }) });
assert.equal(updatedHospitalLogin.status, 200);
const updatedHospitalCookie = updatedHospitalLogin.headers.get('set-cookie').split(';')[0];
const hospitalPatientResponse = await fetch(`${base}/api/patients`, { method: 'POST', headers: { 'Content-Type': 'application/json', Cookie: updatedHospitalCookie }, body: JSON.stringify({ facilityPatientId: 'HP001', name: '病院テスト患者', birthDate: '1960-01-01' }) });
assert.equal(hospitalPatientResponse.status, 201);
const hospitalPatients = await fetch(`${base}/api/patients`, { headers: { Cookie: updatedHospitalCookie } }).then(r => r.json());
assert.equal(hospitalPatients.length, 1);
assert.equal(hospitalPatients[0].name, '病院テスト患者');
const patientResponse = await fetch(`${base}/api/patients`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: auth }, body: JSON.stringify({ facilityPatientId: 'P001', name: 'テスト患者', birthDate: '1950-01-01' }) });
assert.equal(patientResponse.status, 201);
const patient = await patientResponse.json();
assert.match(patient.id, /^patient_/);
const rehabRecordResponse = await fetch(`${base}/api/rehab-records`, {
  method: 'POST',
  headers: { 'Content-Type': 'application/json', Authorization: auth },
  body: JSON.stringify({
    patientId: patient.id,
    therapistName: '療法士テスト',
    preCondition: '開始時安定',
    intervention: '立位練習',
    durationMinutes: 20,
    assistanceLevel: '見守り',
    painBefore: 1,
    painAfter: 1,
    fatigueBefore: 2,
    fatigueAfter: 4,
    outcome: '見守りで完遂',
    nextPlan: '歩行へ進む',
    riskNotes: '転倒注意',
  }),
});
assert.equal(rehabRecordResponse.status, 201);
const rehabRecord = await rehabRecordResponse.json();
assert.equal(rehabRecord.approvalStatus, 'APPROVED');
const rehabRecords = await fetch(`${base}/api/rehab-records?patientId=${patient.id}`, { headers: { Authorization: auth } }).then(r => r.json());
assert.equal(rehabRecords.length, 1);
assert.equal(rehabRecords[0].outcome, '見守りで完遂');
const preRehabSummary = await fetch(`${base}/api/patients/pre-rehab-summary?patientId=${patient.id}`, { headers: { Authorization: auth } }).then(r => r.json());
assert.equal(preRehabSummary.pendingApprovalCount, 0);
const deleteRehabRecordResponse = await fetch(`${base}/api/rehab-records/${rehabRecord.id}`, {
  method: 'DELETE',
  headers: { 'Content-Type': 'application/json', Authorization: auth },
  body: '{}',
});
assert.equal(deleteRehabRecordResponse.status, 200);
assert.equal((await deleteRehabRecordResponse.json()).deletedId, rehabRecord.id);
const rehabRecordsAfterDelete = await fetch(`${base}/api/rehab-records?patientId=${patient.id}`, { headers: { Authorization: auth } }).then(r => r.json());
assert.equal(rehabRecordsAfterDelete.length, 0);
const patients = await fetch(`${base}/api/patients`, { headers: { Authorization: auth } }).then(r => r.json());
assert.equal(patients.length, 1);
assert.equal(patients[0].name, 'テスト患者');
const tinyPng = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=';
const jobResponse = await fetch(`${base}/api/jobs`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: auth }, body: JSON.stringify({ patientId: patient.id, imageDataUrl: tinyPng }) });
assert.equal(jobResponse.status, 202);
const createdJob = await jobResponse.json();
assert.equal(createdJob.status, 'REQUEST');
assert.equal(createdJob.evaluationType, '帳票判定中');
const parallelJobResponse = await fetch(`${base}/api/jobs`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: auth }, body: JSON.stringify({ patientId: patient.id, imageDataUrl: tinyPng }) });
assert.equal(parallelJobResponse.status, 202);
const parallelJob = await parallelJobResponse.json();
assert.notEqual(parallelJob.id, createdJob.id);
const runningJobs = await fetch(`${base}/api/jobs`, { headers: { Authorization: auth } }).then(r => r.json());
assert.ok(runningJobs.some(job => job.id === createdJob.id));
assert.ok(runningJobs.some(job => job.id === parallelJob.id));
let finishedJob, finishedParallelJob;
for (let attempt = 0; attempt < 30; attempt += 1) {
  await new Promise(resolve => setTimeout(resolve, 25));
  [finishedJob, finishedParallelJob] = await Promise.all([
    fetch(`${base}/api/jobs/${createdJob.id}`, { headers: { Authorization: auth } }).then(r => r.json()),
    fetch(`${base}/api/jobs/${parallelJob.id}`, { headers: { Authorization: auth } }).then(r => r.json())
  ]);
  if (finishedJob.status === 'ERROR' && finishedParallelJob.status === 'ERROR') break;
}
assert.equal(finishedJob.status, 'ERROR');
assert.equal(finishedParallelJob.status, 'ERROR');
assert.match(finishedJob.error, /OPENAI_API_KEY/);
const removedAuditEndpoint = await fetch(`${base}/api/audit`, { headers: { Authorization: auth } });
assert.equal(removedAuditEndpoint.status, 404);
const databaseBytes = await readFile(path.join(temp, 'database.json'));
assert.equal(databaseBytes.subarray(0, 6).toString(), 'AIOCR1');
assert.equal(databaseBytes.includes(Buffer.from('テスト患者')), false);
const imageBytes = await readFile(path.join(temp, 'images', createdJob.imageFile));
assert.equal(imageBytes.subarray(0, 6).toString(), 'AIOCR1');
const backupResponse = await fetch(`${base}/api/admin/backup`, { method: 'POST', headers: { Authorization: auth, 'Content-Type': 'application/json' }, body: '{}' });
assert.equal(backupResponse.status, 201);
const backup = await backupResponse.json();
assert.match(backup.backup, /^backup-/);
const backupManifest = JSON.parse(await readFile(path.join(temp, 'backups', backup.backup, 'manifest.json'), 'utf8'));
assert.equal(backupManifest.encrypted, true);
const deleteHistoryResponse = await fetch(`${base}/api/jobs`, { method: 'DELETE', headers: { Authorization: auth, 'Content-Type': 'application/json' }, body: '{}' });
assert.equal(deleteHistoryResponse.status, 200);
const deleteHistoryResult = await deleteHistoryResponse.json();
assert.equal(deleteHistoryResult.deletedCount, 2);
const jobsAfterDelete = await fetch(`${base}/api/jobs`, { headers: { Authorization: auth } }).then(r => r.json());
assert.equal(jobsAfterDelete.length, 0);
await new Promise(resolve => server.close(resolve));
await rm(temp, { recursive: true, force: true });
console.log('standalone smoke test: OK');
