import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';

const temp = await mkdtemp(path.join(tmpdir(), 'standalone-aiocr-'));
process.env.AIOCR_DATA_DIR = temp;
process.env.AIOCR_BACKUP_DIR = path.join(temp, 'backups');
process.env.AIOCR_PORT = '0';
process.env.AIOCR_USERNAME = 'test-admin';
process.env.AIOCR_PASSWORD = 'test-password';
process.env.AIOCR_FACILITY_ID = 'facility-a';
process.env.AIOCR_ENCRYPTION_KEY = 'test-only-encryption-key-32-characters-minimum';
process.env.AIOCR_SKIP_LOCAL_ENV = '1';
const { server } = await import('../server.mjs');
const { inferOcrRoute } = await import('../rehainfo-ocr-definitions.mjs');
assert.deepEqual(inferOcrRoute('WAISⅣ3_01.jpeg'), { testType: 'WAIS_IV_ALL', page: 1 });
assert.deepEqual(inferOcrRoute('WAISⅣ7_13.jpeg'), { testType: 'WAIS_IV_ALL', page: 13 });
assert.deepEqual(inferOcrRoute('SLTA6_01.jpg'), { testType: 'SLTA_ALL', page: 1 });
assert.deepEqual(inferOcrRoute('SLTA12_12.jpg'), { testType: 'SLTA_ALL', page: 12 });
await new Promise(resolve => server.listening ? resolve() : server.once('listening', resolve));
const address = server.address();
const base = `http://127.0.0.1:${address.port}`;
const auth = `Basic ${Buffer.from('test-admin:test-password').toString('base64')}`;
const health = await fetch(`${base}/api/health`).then(r => r.json());
assert.equal(health.ok, true);
assert.equal(health.imageDetail, 'original');
assert.equal(health.reasoningEffort, 'low');
assert.equal(health.retryReasoningEffort, 'high');
const captureHtml = await readFile(new URL('../public/index.html', import.meta.url), 'utf8');
const stylesCss = await readFile(new URL('../public/styles.css', import.meta.url), 'utf8');
assert.match(captureHtml, /id="imageInput"[^>]*accept="image\/\*,application\/pdf,\.pdf"[^>]*multiple/);
assert.doesNotMatch(captureHtml, /id="imageInput"[^>]*capture=/);
assert.match(captureHtml, /id="patientSheetTimeline"/);
assert.match(captureHtml, /患者リハビリ履歴/);
assert.match(captureHtml, /id="evaluationDateOverride"/);
assert.match(captureHtml, /id="therapistSearch"/);
assert.match(captureHtml, /id="therapistSearchList"/);
assert.match(stylesCss, /#patientForm input,\s*#therapistForm input \{\s*font-size: 16px;/);
assert.match(captureHtml, /評価実施日（過去の評価登録可能）/);
assert.match(captureHtml, /id="refreshPatientSheets"/);
assert.match(captureHtml, /id="deleteAllHistory"/);
const captureApp = await readFile(new URL('../public/app.js', import.meta.url), 'utf8');
const cameraApp = await readFile(new URL('../public/camera-capture.js', import.meta.url), 'utf8');
const cameraCss = await readFile(new URL('../public/camera-capture.css', import.meta.url), 'utf8');
const captureCss = await readFile(new URL('../public/capture-layout.css', import.meta.url), 'utf8');
const patientTimelineCss = await readFile(new URL('../public/patient-timeline.css', import.meta.url), 'utf8');
const serverSource = await readFile(new URL('../server.mjs', import.meta.url), 'utf8');
const outcomeCommandApp = await readFile(new URL('../public/outcome-command-center.js', import.meta.url), 'utf8');
assert.match(outcomeCommandApp, /M6 連携品質・バックアップ・エラー追跡/);
assert.match(outcomeCommandApp, /停止理由/);
assert.match(outcomeCommandApp, /loadIntegrationRuns/);
assert.match(outcomeCommandApp, /暗号化バックアップを作成/);
assert.match(outcomeCommandApp, /restorePolicy/);
assert.match(serverSource, /reasoning:\s*\{\s*effort:\s*reasoningEffort\s*\}/);
assert.match(serverSource, /buildRoutedOcrPrompt/);
assert.match(serverSource, /\{\s*1:\s*32,\s*2:\s*29,\s*3:\s*9/);
assert.match(serverSource, /buildBitPage1Prompt/);
assert.match(serverSource, /buildTargetedRetryPrompt/);
assert.match(serverSource, /sheetDetectionReferencePrompt/);
assert.match(serverSource, /aiocr フォルダに保存された実際の画像・PDF/);
assert.match(serverSource, /prompt_cache_key:\s*'rehainfo-sheet-detection-v4-all-reference-forms'/);
assert.match(serverSource, /1=積木模様、2=類似、3=数唱/);
assert.match(serverSource, /1=通常検査得点、2=行動検査得点\+写真課題/);
assert.match(serverSource, /WMS-Rだけは印刷ページ番号から2を引いた値/);
assert.match(serverSource, /image_url:\s*imageUrl,\s*detail:\s*'high'/);
assert.match(serverSource, /confidence >= 0\.65/);
assert.match(serverSource, /prompt_cache_key/);
assert.match(serverSource, /for \(let attempt = 0; attempt < 3; attempt\+\+\)/);
assert.match(serverSource, /\[408, 409, 429\]/);
assert.match(serverSource, /An error occurred while processing/);
assert.match(serverSource, /testType === 'BBS' && filledFieldCount\(ocr\.result\) < 14/);
assert.match(serverSource, /testType === 'STEF' && filledStefTimeCount\(ocr\.result\) < 20/);
assert.match(serverSource, /testType === 'FMA_1' && filledFieldCount\(ocr\.result\) < 33/);
assert.match(captureHtml, /id="cameraSheetOverlay"/);
assert.match(cameraApp, /\/api\/detect-sheet/);
assert.match(cameraApp, /評価シートを判定中/);
assert.match(cameraApp, /showSheetOverlay\(result\.displayName,\s*'recognized'\)/);
assert.doesNotMatch(cameraApp, /認識した評価シート：/);
assert.match(cameraApp, /function liveFrameDataUrl\(\)/);
assert.match(cameraApp, /function startLiveDetection\(\)/);
assert.match(cameraApp, /scheduleLiveDetection\(2000\)/);
assert.match(cameraApp, /detectEvaluationSheet\(imageDataUrl,\s*\{\s*live:\s*true\s*\}\)/);
assert.match(cameraApp, /stopLiveDetection\(\);[\s\S]*?canvas\.width/);
assert.match(cameraApp, /await video\.play\(\);\s*startLiveDetection\(\)/);
assert.match(cameraCss, /\.camera-sheet-overlay/);
assert.match(cameraCss, /data-state="recognized"/);
assert.match(cameraCss, /\.camera-sheet-overlay\s*\{[\s\S]*?top:\s*-58px/);
assert.match(captureHtml, /id="cameraSheetOverlay"[\s\S]*?>シート判定<\/div>/);
assert.doesNotMatch(captureHtml, /A4用紙を撮影|A4用紙を枠内に合わせてください/);
assert.doesNotMatch(captureHtml, /camera-guide-label/);
assert.match(captureHtml, /class="camera-actions">\s*<button id="closeCameraButton"[\s\S]*?<button id="shootCameraButton"/);
assert.doesNotMatch(captureHtml, /camera-header[\s\S]*?id="closeCameraButton"[\s\S]*?<\/header>/);
assert.match(cameraCss, /\.camera-actions \.camera-close-button/);
assert.match(cameraCss, /\.camera-actions\s*\{\s*position:\s*relative/);
assert.match(cameraCss, /\.camera-actions \.camera-close-button\s*\{[\s\S]*?position:\s*absolute;[\s\S]*?left:\s*18px;[\s\S]*?top:\s*50%/);
assert.match(captureHtml, /id="cameraCaptureSlots"/);
assert.match(captureHtml, /id="cameraCaptureCount"/);
assert.match(captureHtml, /id="finishCameraButton"/);
assert.match(captureHtml, /id="shootCameraButton"[\s\S]*?id="finishCameraButton"[\s\S]*?>画像を使用<\/button>/);
assert.match(cameraCss, /\.camera-finish-button\s*\{[\s\S]*?position:\s*absolute;[\s\S]*?right:\s*18px/);
assert.match(cameraApp, /const maxCameraCaptures = 13/);
assert.match(cameraApp, /Array\.from\(\{ length: maxCameraCaptures \}/);
assert.match(cameraApp, /capturedSheets\.filter\(Boolean\)\.forEach\(item => transfer\.items\.add\(item\.file\)\)/);
assert.match(cameraCss, /\.camera-capture-slots/);
assert.match(cameraCss, /display:\s*flex/);
assert.match(cameraCss, /flex-wrap:\s*nowrap/);
assert.match(cameraCss, /overflow-x:\s*scroll/);
assert.match(cameraCss, /touch-action:\s*pan-x/);
assert.match(cameraCss, /flex:\s*0 0 48px/);
assert.doesNotMatch(cameraCss, /aspect-ratio:\s*297\s*\/\s*210/);
assert.doesNotMatch(captureHtml, /id="retakeCameraButton"/);
assert.doesNotMatch(captureHtml, /id="useCameraButton"/);
assert.match(captureHtml, /id="cameraPreviewDialog"/);
assert.match(cameraApp, /activeCaptureIndex = Number\(button\.dataset\.selectCapture\)/);
assert.match(cameraApp, /previewDialog\.showModal\(\)/);
assert.match(cameraApp, /capturedSheets\[activeCaptureIndex\] = \{ file, url: URL\.createObjectURL\(blob\) \}/);
assert.match(cameraCss, /\.camera-capture-slot\.active/);
assert.match(cameraApp, /const coverScale = Math\.max/);
assert.match(cameraApp, /const guideRect = cameraGuide\.getBoundingClientRect\(\)/);
assert.match(cameraApp, /context\.drawImage\(\s*video,\s*sourceX,\s*sourceY,\s*sourceWidth,\s*sourceHeight/);
assert.match(serverSource, /async function detectEvaluationSheet/);
assert.match(serverSource, /rehainfo-sheet-detection-v4-all-reference-forms/);
assert.match(serverSource, /url\.pathname === '\/api\/detect-sheet'/);
assert.match(serverSource, /SLTA_ALL:\s*12/);
assert.match(serverSource, /BIT:\s*7/);
assert.match(serverSource, /CAT_R_ALL:\s*5/);
assert.match(serverSource, /WAIS_IV_ALL:\s*13/);
assert.match(serverSource, /WMSR_ALL:\s*9/);
assert.match(serverSource, /設問番号、採点番号、患者の手書き数字をページ番号として扱わない/);
assert.match(serverSource, /rawPage <= maxPage/);
assert.match(serverSource, /function validateDetectedSheetSet/);
assert.match(serverSource, /同じ用紙を重複して撮影しています/);
assert.match(serverSource, /不足している用紙があります/);
assert.match(serverSource, /用紙の順番が正しくありません/);
assert.match(serverSource, /url\.pathname === '\/api\/validate-sheet-set'/);
assert.doesNotMatch(cameraApp, /await validateCapturedSheetSet/);
assert.match(cameraApp, /imageInput\.dispatchEvent\(new Event\('change'/);
assert.match(captureApp, /validateOcrSheetSet/);
assert.match(captureApp, /backgroundSheetCheckToken/);
assert.match(captureApp, /バックグラウンドで評価用紙を確認しています/);
assert.match(captureApp, /function cancelBackgroundSheetCheck/);
assert.match(captureApp, /backgroundSheetCheckController\?\.abort\(\)/);
assert.match(captureApp, /startOcrWithPriority/);
assert.match(captureApp, /correctImagesWithPriority/);
const adminApp = await readFile(new URL('../public/admin.js', import.meta.url), 'utf8');
assert.match(adminApp, /hospitals=\[hospital,\.\.\.hospitals\.filter/);
assert.match(adminApp, /renderHospitals\(\);event\.currentTarget\.reset/);
assert.match(adminApp, /data-edit-hospital=/);
assert.match(adminApp, /method:'PUT'/);
assert.match(captureApp, /resizeLongEdge\(dataUrl,maxLongEdge=2048\)/);
assert.match(captureApp, /correctFullEvaluationSheet\(original\)/);
assert.match(captureApp, /removeDocumentShadow\(dataUrl\)/);
assert.match(captureApp, /alignTableForHumanViewing\(shadowRemoved\)/);
assert.match(captureApp, /state\.imageDataUrls=optimized\.map\(item=>item\.imageDataUrl\)/);
assert.match(captureApp, /Math\.min\(4,count\)/);
assert.match(captureApp, /fileName:item\.fileName,pageNumber:item\.pageNumber/);
assert.match(captureApp, /function shortItemText\(value\)/);
assert.match(captureApp, /function visibleResultFields\(result\)/);
assert.match(captureApp, /bitPage2=.*BIT_2_/);
assert.match(captureApp, /chars\.length>16/);
assert.match(captureApp, /itemTextMarkup\(field\.label\)/);
assert.match(captureApp, /const bitPage1=result\?\.testType==='BIT'.*BIT_\\d\+_/);
assert.match(captureApp, /bit-page1-min/);
assert.match(captureApp, /bitPageNumber===1\?\.15\+anchorY\*\.88:anchorY/);
assert.match(captureApp, /if\(bitPage1\)\{\s*return fields\.map/);
assert.match(captureApp, /ocr-value anchored plain/);
assert.match(captureApp, /landscape-overlay/);
assert.match(captureApp, /const bitPageNumber=Number/);
assert.match(captureCss, /\.ocr-value\.bit-page1-min\{min-width:0;padding:1px 5px;transform:translate\(-50%,-50%\);font-size:12px/);
assert.match(captureCss, /\.photo-control \.patient-search-input,\s*\.photo-control \.therapist-search-input \{\s*font-size: 16px;/);
assert.match(cameraCss, /@media \(max-width: 760px\)[\s\S]*?\.photo-control \.patient-search-input,\s*\.photo-control \.therapist-search-input \{\s*font-size: 16px;/);
assert.match(cameraCss, /\.photo-input-row > \.camera-open-button,\s*\.image-correct-button,\s*\.start-control \.compact-ocr-button,\s*\.capture-stop-button \{\s*font-size: 14px !important;/);
assert.match(cameraCss, /\.photo-control \.evaluation-date-override input \{\s*font-size: 14px !important;/);
assert.match(captureApp, /function positionBitOverlays\(overlay\)/);
assert.match(captureApp, /translateY\(\$\{boxHeight\+3\}px\)/);
assert.match(captureApp, /class="first-result-row"/);
assert.match(captureApp, /optimizedValueControl\(field,'batch-field-value'\)/);
assert.doesNotMatch(captureApp, /first-result-table/);
assert.match(captureApp, /pdfjsLib\.getDocument/);
assert.match(captureApp, /function renderPatientSheetTimeline\(\)/);
assert.match(captureApp, /function renderClinicalFlow\(patientId\)/);
assert.match(captureApp, /function clinicalEvaluationRuns\(jobs\)/);
assert.match(captureApp, /ページ・1回の評価/);
assert.match(captureApp, /function clinicalEvaluationDate\(job\)/);
assert.match(captureApp, /評価日不明/);
assert.match(captureApp, /evaluationDateOverride/);
assert.match(captureApp, /therapistName=selectedTherapistName\(\)/);
assert.match(captureApp, /evaluationDateOverride'\)\.value=todayValue\(\)/);
assert.match(serverSource, /jobEvaluationDate/);
assert.match(serverSource, /evaluationDateOverride/);
assert.match(captureApp, /\/api\/rehab-records/);
assert.doesNotMatch(captureApp, /id="patientClinicalFlow"/);
assert.doesNotMatch(captureApp, /今回の記録を追加|rehabRecordForm/);
assert.match(serverSource, /rehabRecords/);
assert.match(serverSource, /pre-rehab-summary/);
assert.doesNotMatch(captureApp, /THERAPIST_LEVELS|therapistFeatures|療法士区分/);
assert.match(serverSource, /therapistName/);
assert.match(captureApp, /state\.selectedPatientTimelineId=ocrPatientId/);
assert.match(captureApp, /患者欄にも追加しました/);
assert.match(captureApp, /careStageLabel/);
assert.match(captureApp, /data-discharge-job/);
assert.match(captureApp, /data-undo-discharge-job/);
assert.match(patientTimelineCss, /\.patient-sheet-card\s*\{[\s\S]*?flex-direction:\s*column;[\s\S]*?min-height:\s*350px/);
assert.match(patientTimelineCss, /\.discharge-button\s*\{[\s\S]*?position:\s*absolute;[\s\S]*?top:\s*10px;[\s\S]*?right:\s*10px/);
assert.match(patientTimelineCss, /\.undo-discharge-button\s*\{[\s\S]*?position:\s*absolute;[\s\S]*?top:\s*10px;[\s\S]*?right:\s*10px/);
assert.match(captureApp, /data-delete-job/);
assert.match(serverSource, /deletedId/);
assert.match(captureApp, /途中経過に戻す/);
assert.match(captureApp, /summaryDischarge/);
assert.doesNotMatch(captureApp, /id="summaryDischarge"/);
assert.match(captureApp, /summaryUndoDischarge/);
assert.match(captureApp, /switchSummaryCareStage/);
assert.match(captureApp, /alreadyDischarged/);
assert.match(captureApp, /dischargeWarningsShown/);
assert.match(serverSource, /hasExistingDischarge/);
assert.match(captureApp, /id="familySummary"/);
assert.match(captureApp, /id="patientSummary"/);
assert.match(serverSource, /familySummary/);
assert.match(serverSource, /patientSummary/);
assert.match(captureApp, /stage-history-row/);
assert.match(captureApp, /評価用紙/);
assert.match(captureApp, /id="rehabSummary"/);
assert.match(captureApp, /initial-summary/);
assert.match(captureApp, /id="generateInitialSummary"/);
assert.match(captureApp, /サマリ生成/);
assert.match(captureApp, /id="progressSummary"/);
assert.match(captureApp, /generateProgressSummary/);
assert.match(captureApp, /id="dischargeSummary"/);
assert.match(captureApp, /generateDischargeSummary/);
assert.match(serverSource, /initial-summary/);
assert.match(serverSource, /rehabSummary/);
assert.match(serverSource, /generateRehabSummary/);
assert.match(serverSource, /generateProgressSummary/);
assert.match(serverSource, /previousSameSheetJob/);
assert.match(serverSource, /generateDischargeSummary/);
assert.match(serverSource, /undoDischargeMatch/);
assert.match(serverSource, /job\.careStage = 'FOLLOW_UP'/);
assert.match(serverSource, /assessmentGroupId/);
assert.match(serverSource, /rebuildAssessmentGroups/);
assert.match(serverSource, /safeText\(job\.therapistName\)\.toLowerCase\(\)/);
assert.match(serverSource, /const assessmentSet = expectedPageCount/);
assert.match(serverSource, /missingPages/);
assert.match(captureApp, /不足：/);
assert.match(captureApp, /全ページ確認済み/);
assert.match(captureApp, /初診サマリ/);
assert.match(captureApp, /全ページのOCR結果/);
assert.match(captureApp, /batch-field-value/);
assert.match(captureApp, /修正内容を保存/);
assert.match(captureApp, /const columns=/);
assert.match(captureApp, /sideCandidates/);
assert.match(captureApp, /class="ocr-value\$\{dense/);
assert.match(captureApp, /collisions\*10000/);
assert.match(serverSource, /SLTA_/);
assert.match(serverSource, /SLTA_.*TEXT.*filter|filter.*SLTA_.*TEXT/s);
assert.match(captureApp, /evaluationName.*SLTA/);
assert.match(captureApp, /初診サマリ/);
assert.match(captureApp, /method:'DELETE'/);
assert.match(captureApp, /OCR用に長辺2400px以下へ最適化済み/);
assert.match(captureApp, /const median=channel=>/);
assert.match(captureApp, /const sustainedBounds=/);
assert.match(captureHtml, /id="batchComparisons"/);
assert.match(captureApp, /function renderBatchComparisons\(\)/);
assert.match(captureApp, /state\.jobs\.slice\(0,20\)/);
assert.match(captureApp, /showAllHistory/);
assert.match(captureApp, /20件表示に戻す/);
assert.match(captureApp, /OCR結果（テキスト）/);
assert.match(captureApp, /String\(field\.value\?\?''\)\.trim\(\)!==''/);
assert.match(captureApp, /_TEXT_/);
assert.match(captureApp, /function alignResultOverlays\(\)/);
assert.match(captureApp, /class="field-label-text"/);
assert.doesNotMatch(captureApp, /class="field-label"/);
assert.match(captureApp, /style="left:\$\{x\}%;top:\$\{y\}%"/);
const denied = await fetch(`${base}/api/patients`);
assert.equal(denied.status, 401);
const loginResponse = await fetch(`${base}/api/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username: 'test-admin', password: 'test-password' }) });
assert.equal(loginResponse.status, 200);
const loginResult = await loginResponse.json();
assert.equal(loginResult.role, 'ADMIN');
assert.equal(loginResult.redirect, '/admin.html');
const sessionCookie = loginResponse.headers.get('set-cookie').split(';')[0];
const sessionPatientsResponse = await fetch(`${base}/api/patients`, { headers: { Cookie: sessionCookie } });
assert.equal(sessionPatientsResponse.status, 200);
const adminPageResponse = await fetch(`${base}/admin.html`, { headers: { Cookie: sessionCookie } });
assert.equal(adminPageResponse.status, 200);
const hospitalCreateResponse = await fetch(`${base}/api/admin/hospitals`, { method: 'POST', headers: { 'Content-Type': 'application/json', Cookie: sessionCookie }, body: JSON.stringify({ name: 'テスト病院', loginName: 'hospital-test', password: 'hospital-password' }) });
assert.equal(hospitalCreateResponse.status, 201);
const hospitalAccount = await hospitalCreateResponse.json();
assert.equal(hospitalAccount.name, 'テスト病院');
assert.equal(hospitalAccount.passwordHash, undefined);
const hospitalLoginResponse = await fetch(`${base}/api/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username: 'hospital-test', password: 'hospital-password' }) });
assert.equal(hospitalLoginResponse.status, 200);
const hospitalLoginResult = await hospitalLoginResponse.json();
assert.equal(hospitalLoginResult.role, 'HOSPITAL');
assert.equal(hospitalLoginResult.redirect, '/');
const hospitalCookie = hospitalLoginResponse.headers.get('set-cookie').split(';')[0];
const hospitalAdminDenied = await fetch(`${base}/api/admin/hospitals`, { headers: { Cookie: hospitalCookie } });
assert.equal(hospitalAdminDenied.status, 403);
const hospitalAdminPageDenied = await fetch(`${base}/admin.html`, { headers: { Cookie: hospitalCookie } });
assert.equal(hospitalAdminPageDenied.status, 403);
const hospitalUpdateResponse = await fetch(`${base}/api/admin/hospitals/${hospitalAccount.id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json', Cookie: sessionCookie }, body: JSON.stringify({ name: '更新テスト病院', loginName: 'hospital-updated', password: 'updated-password' }) });
assert.equal(hospitalUpdateResponse.status, 200);
const updatedHospitalAccount = await hospitalUpdateResponse.json();
assert.equal(updatedHospitalAccount.name, '更新テスト病院');
assert.equal(updatedHospitalAccount.loginName, 'hospital-updated');
assert.equal(updatedHospitalAccount.passwordHash, undefined);
const invalidatedHospitalSession = await fetch(`${base}/api/patients`, { headers: { Cookie: hospitalCookie } });
assert.equal(invalidatedHospitalSession.status, 401);
const oldHospitalLogin = await fetch(`${base}/api/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username: 'hospital-test', password: 'hospital-password' }) });
assert.equal(oldHospitalLogin.status, 401);
const updatedHospitalLogin = await fetch(`${base}/api/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username: 'hospital-updated', password: 'updated-password' }) });
assert.equal(updatedHospitalLogin.status, 200);
const updatedHospitalCookie = updatedHospitalLogin.headers.get('set-cookie').split(';')[0];
const hospitalPatientResponse = await fetch(`${base}/api/patients`, { method: 'POST', headers: { 'Content-Type': 'application/json', Cookie: updatedHospitalCookie }, body: JSON.stringify({ facilityPatientId: 'HP001', name: '病院テスト患者', birthDate: '1960-01-01' }) });
assert.equal(hospitalPatientResponse.status, 201);
const hospitalPatients = await fetch(`${base}/api/patients`, { headers: { Cookie: updatedHospitalCookie } }).then(r => r.json());
assert.equal(hospitalPatients.length, 1);
assert.equal(hospitalPatients[0].name, '病院テスト患者');
const patientResponse = await fetch(`${base}/api/patients`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: auth }, body: JSON.stringify({ facilityPatientId: 'P001', name: 'テスト患者', birthDate: '1950-01-01' }) });
assert.equal(patientResponse.status, 201);
const patient = await patientResponse.json();
assert.match(patient.id, /^patient_/);
const rehabRecordResponse = await fetch(`${base}/api/rehab-records`, {
  method: 'POST',
  headers: { 'Content-Type': 'application/json', Authorization: auth },
  body: JSON.stringify({
    patientId: patient.id,
    therapistName: '療法士テスト',
    preCondition: '開始時安定',
    intervention: '立位練習',
    durationMinutes: 20,
    assistanceLevel: '見守り',
    painBefore: 1,
    painAfter: 1,
    fatigueBefore: 2,
    fatigueAfter: 4,
    outcome: '見守りで完遂',
    nextPlan: '歩行へ進む',
    riskNotes: '転倒注意',
  }),
});
assert.equal(rehabRecordResponse.status, 201);
const rehabRecord = await rehabRecordResponse.json();
assert.equal(rehabRecord.approvalStatus, 'APPROVED');
const rehabRecords = await fetch(`${base}/api/rehab-records?patientId=${patient.id}`, { headers: { Authorization: auth } }).then(r => r.json());
assert.equal(rehabRecords.length, 1);
assert.equal(rehabRecords[0].outcome, '見守りで完遂');
const preRehabSummary = await fetch(`${base}/api/patients/pre-rehab-summary?patientId=${patient.id}`, { headers: { Authorization: auth } }).then(r => r.json());
assert.equal(preRehabSummary.pendingApprovalCount, 0);
const deleteRehabRecordResponse = await fetch(`${base}/api/rehab-records/${rehabRecord.id}`, {
  method: 'DELETE',
  headers: { 'Content-Type': 'application/json', Authorization: auth },
  body: '{}',
});
assert.equal(deleteRehabRecordResponse.status, 200);
assert.equal((await deleteRehabRecordResponse.json()).deletedId, rehabRecord.id);
const rehabRecordsAfterDelete = await fetch(`${base}/api/rehab-records?patientId=${patient.id}`, { headers: { Authorization: auth } }).then(r => r.json());
assert.equal(rehabRecordsAfterDelete.length, 0);
const patients = await fetch(`${base}/api/patients`, { headers: { Authorization: auth } }).then(r => r.json());
const ordinaryPatients = patients.filter(item => !item.facilityPatientId.startsWith('RV'));
assert.equal(ordinaryPatients.length, 1);
assert.equal(ordinaryPatients[0].name, 'テスト患者');
assert.deepEqual(patients.filter(item => item.facilityPatientId.startsWith('RV')).map(item => item.facilityPatientId).sort(), ['RV001', 'RV002', 'RV003']);
const voiceSessionResponse = await fetch(`${base}/api/rehab-voice/sessions`, {
  method: 'POST',
  headers: { 'Content-Type': 'application/json', Authorization: auth },
  body: JSON.stringify({ id: 'rehab-voice-smoke-1', patientId: patient.id, patientLabel: `TEST001｜${patient.name}`, therapistLabel: 'PT001｜Test Therapist', duration: '00:20:00', transcript: '患者：テスト会話', patientLog: 'テストログ', concerns: 'なし', consultations: 'なし', audioSource: 'recorded', audioDataUrl: 'data:audio/webm;base64,V0VCTQ==' }),
});
assert.equal(voiceSessionResponse.status, 201);
const voiceSessions = await fetch(`${base}/api/rehab-voice/sessions`, { headers: { Authorization: auth } }).then(r => r.json());
assert.equal(voiceSessions.length, 1);
assert.equal(voiceSessions[0].hasAudio, true);
const voiceAudioResponse = await fetch(`${base}/api/rehab-voice/sessions/rehab-voice-smoke-1/audio`, { headers: { Authorization: auth } });
assert.equal(voiceAudioResponse.status, 200);
assert.equal(voiceAudioResponse.headers.get('content-type'), 'audio/webm');
const planContextSaveResponse = await fetch(`${base}/api/rehab-plan-context`, {
  method: 'PUT', headers: { 'Content-Type': 'application/json', Authorization: auth },
  body: JSON.stringify({ patientId: patient.id, diagnosis: '脳梗塞', preHospitalLife: '屋内歩行自立', patientGoals: '自宅へ戻る', dataStatus: 'VERIFIED', lastReviewedDate: '2026-08-02', reviewedBy: 'Test Therapist' }),
});
assert.equal(planContextSaveResponse.status, 200);
assert.equal((await planContextSaveResponse.json()).dataStatus, 'VERIFIED');
const planContext = await fetch(`${base}/api/rehab-plan-context?patientId=${patient.id}`, { headers: { Authorization: auth } }).then(r => r.json());
assert.equal(planContext.diagnosis, '脳梗塞');
const planSourceResponse = await fetch(`${base}/api/rehab-plans/source?patientId=${patient.id}`, { headers: { Authorization: auth } });
assert.equal(planSourceResponse.status, 200);
const planSource = await planSourceResponse.json();
assert.equal(planSource.latestVoice.patientLog, 'テストログ');
assert.equal(planSource.planContext.patientGoals, '自宅へ戻る');
const generatePlanResponse = await fetch(`${base}/api/rehab-plans/generate`, {
  method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: auth }, body: JSON.stringify({ patientId: patient.id }),
});
assert.equal(generatePlanResponse.status, 503);
const createPlanResponse = await fetch(`${base}/api/rehab-plans`, {
  method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: auth },
  body: JSON.stringify({ patientId: patient.id, planType: 'INITIAL', evaluationDate: '2026-08-02', diagnosis: 'Smoke diagnosis', patientWishes: 'Walk home', shortTermGoals: 'Stand safely', status: 'DRAFT' }),
});
assert.equal(createPlanResponse.status, 201);
const rehabPlan = await createPlanResponse.json();
assert.equal(rehabPlan.version, 1);
assert.equal(rehabPlan.status, 'DRAFT');
const updatePlanResponse = await fetch(`${base}/api/rehab-plans/${rehabPlan.id}`, {
  method: 'PUT', headers: { 'Content-Type': 'application/json', Authorization: auth },
  body: JSON.stringify({ ...rehabPlan, longTermGoals: 'Return home', status: 'CONFIRMED' }),
});
assert.equal(updatePlanResponse.status, 200);
const confirmedPlan = await updatePlanResponse.json();
assert.equal(confirmedPlan.status, 'CONFIRMED');
assert.equal(confirmedPlan.revisions.length, 1);
const rehabPlans = await fetch(`${base}/api/rehab-plans?patientId=${patient.id}`, { headers: { Authorization: auth } }).then(r => r.json());
assert.equal(rehabPlans.length, 1);
const fimKeys = ['eating','grooming','bathing','dressingUpper','dressingLower','toileting','bladder','bowel','transferBedChair','transferToilet','transferTubShower','locomotion','stairs','comprehension','expression','socialInteraction','problemSolving','memory'];
const admissionFimResponse = await fetch(`${base}/api/fim-assessments`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: auth }, body: JSON.stringify({ patientId: patient.id, stage: 'ADMISSION', evaluationDate: '2026-08-01', evaluator: 'Test Therapist', status: 'CONFIRMED', scores: Object.fromEntries(fimKeys.map(key => [key, 3])) }) });
assert.equal(admissionFimResponse.status, 201);
assert.equal((await admissionFimResponse.json()).total, 54);
const periodicFimResponse = await fetch(`${base}/api/fim-assessments`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: auth }, body: JSON.stringify({ patientId: patient.id, stage: 'PERIODIC', evaluationDate: '2026-08-11', evaluator: 'Test Therapist', status: 'CONFIRMED', scores: Object.fromEntries(fimKeys.map(key => [key, 4])) }) });
assert.equal(periodicFimResponse.status, 201);
assert.equal((await periodicFimResponse.json()).total, 72);
const fimSummaryResponse = await fetch(`${base}/api/fim-assessments?patientId=${patient.id}`, { headers: { Authorization: auth } });
assert.equal(fimSummaryResponse.status, 200);
const fimSummary = await fimSummaryResponse.json();
assert.equal(fimSummary.gain, 18);
assert.equal(fimSummary.efficiency, 1.8);
const wardProfileResponse = await fetch(`${base}/api/recovery-ward-profile`, { method: 'PUT', headers: { 'Content-Type': 'application/json', Authorization: auth }, body: JSON.stringify({ patientId: patient.id, wardName: '東2病棟', onsetDate: '2026-07-20', admissionDate: '2026-08-01', plannedDischargeDate: '2026-11-30', diseaseCategory: '脳血管疾患', limitDays: 150, fimIntervalDays: 14 }) });
assert.equal(wardProfileResponse.status, 200);
const wardProfile = await wardProfileResponse.json();
assert.equal(wardProfile.summary.limitDate, '2026-12-28');
assert.equal(wardProfile.summary.nextDue, '2026-08-25');
const dischargeInitializeResponse = await fetch(`${base}/api/discharge-board/initialize`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: auth }, body: JSON.stringify({ patientId: patient.id }) });
assert.equal(dischargeInitializeResponse.status, 200);
const dischargeInitialized = await dischargeInitializeResponse.json();
assert.equal(dischargeInitialized.tasks.length, 14);
const dischargeSuggestionResponse = await fetch(`${base}/api/discharge-board/suggest-schedule`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: auth }, body: JSON.stringify({ patientId: patient.id }) });
assert.equal(dischargeSuggestionResponse.status, 200);
const dischargeSuggested = await dischargeSuggestionResponse.json();
assert.equal(dischargeSuggested.changed, 14);
const homeVisitTask = dischargeSuggested.tasks.find(task => task.key === 'HOME_VISIT');
assert.equal(homeVisitTask.owner, 'PT・OT・MSW');
assert.equal(homeVisitTask.dueDate, '2026-11-02');
assert.equal(homeVisitTask.ownerSource, 'PROPOSED');
assert.equal(dischargeSuggested.trackingRate, 0);
assert.equal(dischargeSuggested.untracked, 14);
const toiletingTask = dischargeSuggested.tasks.find(task => task.key === 'TOILETING');
const dischargeUpdateResponse = await fetch(`${base}/api/discharge-board`, { method: 'PUT', headers: { 'Content-Type': 'application/json', Authorization: auth }, body: JSON.stringify({ patientId: patient.id, tasks: [{ id: toiletingTask.id, status: 'BLOCKING', priority: 'HIGH', owner: 'OT', dueDate: '2026-08-20', note: '夜間動作確認' }] }) });
assert.equal(dischargeUpdateResponse.status, 200);
const dischargeBoard = await dischargeUpdateResponse.json();
assert.equal(dischargeBoard.blocking, 1);
assert.equal(dischargeBoard.ownerMissing, 0);
assert.equal(dischargeBoard.trackingRate, 7);
assert.equal(dischargeBoard.tracked, 1);
assert.equal(dischargeBoard.tasks.find(task => task.key === 'TOILETING').ownerSource, 'USER_CONFIRMED');
const conferenceBriefResponse = await fetch(`${base}/api/conference-brief?patientId=${patient.id}`, { headers: { Authorization: auth } });
assert.equal(conferenceBriefResponse.status, 200);
const conferenceBrief = await conferenceBriefResponse.json();
assert.equal(conferenceBrief.discharge.blocking, 1);
assert.equal(conferenceBrief.sources.includes('FIM評価・推移'), true);
assert.equal(conferenceBrief.decisions.every(item => item.source), true);
assert.equal(Array.isArray(conferenceBrief.contradictions), true);
assert.equal(conferenceBrief.generationMode, 'RULE_BASED');
assert.equal(conferenceBrief.evidenceCoverage, 100);
assert.equal(conferenceBrief.readyForConference, true);
assert.equal(conferenceBrief.generationMs < 300000, true);
const conferenceAiNoKeyResponse = await fetch(`${base}/api/conference-brief/ai`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: auth }, body: JSON.stringify({ patientId: patient.id }) });
assert.equal(conferenceAiNoKeyResponse.status, 503);
const conferenceResponse = await fetch(`${base}/api/conferences`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: auth }, body: JSON.stringify({ patientId: patient.id, heldAt: '2026-08-22', participants: '医師、看護、PT、OT、ST、MSW', minutes: '退院阻害要因を確認', decision: '家屋確認を実施', action: '家屋確認日を家族と調整', owner: 'MSW', dueDate: '2026-08-25', sources: conferenceBrief.sources }) });
assert.equal(conferenceResponse.status, 201);
const savedConference = await conferenceResponse.json();
assert.equal(savedConference.owner, 'MSW');
const conferenceUpdateResponse = await fetch(`${base}/api/conferences/${savedConference.id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json', Authorization: auth }, body: JSON.stringify({ heldAt: '2026-08-22', participants: '医師、看護、PT、OT、ST、MSW、栄養', minutes: '多職種で再確認', decision: '家屋確認と家族指導を実施', action: '家屋確認日を家族と調整', owner: 'MSW', dueDate: '2026-08-26' }) });
assert.equal(conferenceUpdateResponse.status, 200);
const updatedConference = await conferenceUpdateResponse.json();
assert.equal(updatedConference.revisions.length, 1);
assert.equal(updatedConference.decision, '家屋確認と家族指導を実施');
const conferenceHistoryResponse = await fetch(`${base}/api/conference-brief?patientId=${patient.id}`, { headers: { Authorization: auth } });
const conferenceWithHistory = await conferenceHistoryResponse.json();
assert.equal(conferenceWithHistory.conferenceHistory.length, 1);
const fimExportResponse = await fetch(`${base}/api/fim-export.csv`, { headers: { Authorization: auth } });
assert.equal(fimExportResponse.status, 200);
assert.match(fimExportResponse.headers.get('content-type'), /text\/csv/);
assert.match(await fimExportResponse.text(), /facilityPatientId/);
const managementExportResponse = await fetch(`${base}/api/outcome-management-report.csv`, { headers: { Authorization: auth } });
assert.equal(managementExportResponse.status, 200);
assert.match(managementExportResponse.headers.get('content-type'), /text\/csv/);
const managementCsv = await managementExportResponse.text();
assert.match(managementCsv, /平均FIM利得/);
assert.match(managementCsv, /平均参考単位数/);
assert.doesNotMatch(managementCsv, /patientName|facilityPatientId/);
const monthlyReportResponse = await fetch(`${base}/api/outcome-monthly-report.html`, { headers: { Authorization: auth } });
assert.equal(monthlyReportResponse.status, 200);
assert.match(monthlyReportResponse.headers.get('content-type'), /text\/html/);
const monthlyReport = await monthlyReportResponse.text();
assert.match(monthlyReport, /回復期病棟 月次アウトカム報告/);
assert.match(monthlyReport, /正式な行政提出様式や診療報酬請求値としては使用できません/);
assert.doesNotMatch(monthlyReport, new RegExp(patient.name));
const fimOcrNoKeyResponse = await fetch(`${base}/api/fim-ocr`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: auth }, body: JSON.stringify({ imageDataUrl: 'data:image/png;base64,iVBORw0KGgo=' }) });
assert.equal(fimOcrNoKeyResponse.status, 503);
const importRow = { facilityPatientId: patient.facilityPatientId, stage: 'DISCHARGE', evaluationDate: '2026-08-21', evaluator: 'CSV Test', status: 'CONFIRMED', locomotionMode: 'WALK', ...Object.fromEntries(fimKeys.map(key => [key, '5'])) };
const fimImportResponse = await fetch(`${base}/api/fim-import`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: auth }, body: JSON.stringify({ rows: [importRow] }) });
assert.equal(fimImportResponse.status, 200);
assert.equal((await fimImportResponse.json()).imported, 1);
const stagnationFimResponse = await fetch(`${base}/api/fim-assessments`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: auth }, body: JSON.stringify({ patientId: patient.id, stage: 'PERIODIC', evaluationDate: '2026-08-28', evaluator: 'Test Therapist', status: 'CONFIRMED', scores: Object.fromEntries(fimKeys.map(key => [key, 5])) }) });
assert.equal(stagnationFimResponse.status, 201);
const outcomeCenterResponse = await fetch(`${base}/api/outcome-command-center`, { headers: { Authorization: auth } });
assert.equal(outcomeCenterResponse.status, 200);
const outcomeCenter = await outcomeCenterResponse.json();
assert.equal(outcomeCenter.summary.patientCount, 4);
assert.equal(outcomeCenter.summary.planReviewCount >= 1, true);
assert.equal(outcomeCenter.summary.fimRegisteredCount, 1);
assert.equal(outcomeCenter.summary.dataQualityIssueCount >= 1, true);
assert.equal(outcomeCenter.summary.earlyWarningCount >= 1, true);
assert.equal(outcomeCenter.earlyWarnings.some(item => item.patientId === patient.id && item.type === 'FIM_STAGNATION' && item.confidence === 0.8), true);
assert.equal(outcomeCenter.earlyWarnings.every(item => item.evidence.length && item.nextData && item.action && item.ownerCandidate), true);
assert.equal(outcomeCenter.warningAudit.some(item => item.exclusions.length > 0), true);
assert.equal(outcomeCenter.blockerRanking.some(item => item.key === 'TOILETING' && item.patients === 1), true);
assert.equal(outcomeCenter.performanceIndexSimulation.eligiblePatients, 1);
assert.equal(outcomeCenter.performanceIndexSimulation.currentIndex > 0, true);
assert.match(outcomeCenter.performanceIndexSimulation.disclaimer, /請求・届出値には使用できません/);
assert.equal(outcomeCenter.managementDashboard.groups.length, 3);
assert.equal(outcomeCenter.managementDashboard.groups.some(group => group.dimension === 'ward' && group.rows.some(row => row.patients >= 1)), true);
assert.match(outcomeCenter.managementDashboard.definitions.homeReturnRate, /分子/);
assert.equal(outcomeCenter.managementDashboard.benchmark.minimumGroupSize, 3);
assert.match(outcomeCenter.managementDashboard.benchmark.privacyNote, /患者名・患者IDは出力しません/);
assert.equal(outcomeCenter.managementDashboard.benchmark.rows.every(row => row.patients >= 3), true);
assert.equal(outcomeCenter.managementDashboard.therapyComparison.totalPatients, 4);
assert.equal(outcomeCenter.managementDashboard.therapyComparison.rows.every(row => row.patients >= 3), true);
assert.match(outcomeCenter.managementDashboard.therapyComparison.note, /因果関係を示しません/);
assert.match(outcomeCenter.managementDashboard.definitions.therapyUnits, /正式な診療報酬請求単位ではなく/);
const performanceSimulationResponse = await fetch(`${base}/api/outcome-performance-simulation?additionalMotorFim=2&reducedStayDays=5`, { headers: { Authorization: auth } });
assert.equal(performanceSimulationResponse.status, 200);
const performanceSimulation = await performanceSimulationResponse.json();
assert.equal(performanceSimulation.simulatedIndex > performanceSimulation.currentIndex, true);
const stagnationWarning = outcomeCenter.earlyWarnings.find(item => item.patientId === patient.id && item.type === 'FIM_STAGNATION');
const warningActionedResponse = await fetch(`${base}/api/outcome-warnings/${stagnationWarning.id}/review`, { method: 'PUT', headers: { 'Content-Type': 'application/json', Authorization: auth }, body: JSON.stringify({ status: 'ACTIONED', note: 'カンファレンスで確認' }) });
assert.equal(warningActionedResponse.status, 200);
const outcomeAfterActioned = await fetch(`${base}/api/outcome-command-center`, { headers: { Authorization: auth } }).then(response => response.json());
assert.equal(outcomeAfterActioned.warningMetrics.actioned >= 1, true);
assert.equal(outcomeAfterActioned.warningMetrics.actionRate > 0, true);
assert.equal(outcomeAfterActioned.warningOutcomeComparisons.some(item => item.warningId === stagnationWarning.id && item.status === 'PENDING'), true);
const improvedFimResponse = await fetch(`${base}/api/fim-assessments`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: auth }, body: JSON.stringify({ patientId: patient.id, stage: 'PERIODIC', evaluationDate: '2026-09-05', evaluator: 'Test Therapist', status: 'CONFIRMED', scores: Object.fromEntries(fimKeys.map(key => [key, 6])) }) });
assert.equal(improvedFimResponse.status, 201);
const outcomeAfterImprovement = await fetch(`${base}/api/outcome-command-center`, { headers: { Authorization: auth } }).then(response => response.json());
const validatedWarning = outcomeAfterImprovement.warningOutcomeComparisons.find(item => item.warningId === stagnationWarning.id);
assert.equal(validatedWarning.status, 'IMPROVED');
assert.equal(validatedWarning.delta, 18);
const warningFalseResponse = await fetch(`${base}/api/outcome-warnings/${stagnationWarning.id}/review`, { method: 'PUT', headers: { 'Content-Type': 'application/json', Authorization: auth }, body: JSON.stringify({ status: 'FALSE_ALERT', note: '評価条件差による変動' }) });
assert.equal(warningFalseResponse.status, 200);
assert.equal((await warningFalseResponse.json()).revisions.length, 1);
const outcomeAfterFalse = await fetch(`${base}/api/outcome-command-center`, { headers: { Authorization: auth } }).then(response => response.json());
assert.equal(outcomeAfterFalse.warningMetrics.falseAlerts >= 1, true);
assert.equal(outcomeAfterFalse.warningMetrics.falseAlertRate > 0, true);
assert.equal(outcomeCenter.patients.find(item => item.patientId === patient.id).fimGain, 36);
assert.equal(outcomeCenter.patients.find(item => item.patientId === patient.id).dischargeBlocking, 1);
assert.equal(outcomeCenter.patients.some(item => item.patientId === patient.id && item.planStatus === 'CONFIRMED'), true);
assert.equal(outcomeCenter.goals.some(goal => goal.key === 'homeReturnRate' && goal.publicBaseline === 83), true);
const goalUpdateResponse = await fetch(`${base}/api/outcome-goals`, { method: 'PUT', headers: { 'Content-Type': 'application/json', Authorization: auth }, body: JSON.stringify({ key: 'homeReturnRate', target: 86 }) });
assert.equal(goalUpdateResponse.status, 200);
assert.equal((await goalUpdateResponse.json()).targetType, 'HOSPITAL_DEFINED');
const snapshotResponse = await fetch(`${base}/api/outcome-snapshots`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: auth }, body: JSON.stringify({ period: '2026-08', values: { homeReturnRate: 84.5, fimGain: 28.1, performanceIndex: 48.2 }, dataType: 'SAMPLE', note: 'smoke sample' }) });
assert.equal(snapshotResponse.status, 200);
assert.equal((await snapshotResponse.json()).dataType, 'SAMPLE');
const outcomeAfterSnapshot = await fetch(`${base}/api/outcome-command-center`, { headers: { Authorization: auth } }).then(response => response.json());
assert.equal(outcomeAfterSnapshot.managementDashboard.monthlyTrend.some(item => item.period === '2026-08' && item.targetDifference.homeReturnRate === -1.5), true);
const actionResponse = await fetch(`${base}/api/outcome-actions`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: auth }, body: JSON.stringify({ patientId: patient.id, category: 'DISCHARGE', title: '家屋確認', owner: 'MSW', dueDate: '2026-08-15' }) });
assert.equal(actionResponse.status, 201);
const outcomeAction = await actionResponse.json();
const completeActionResponse = await fetch(`${base}/api/outcome-actions/${outcomeAction.id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json', Authorization: auth }, body: JSON.stringify({ status: 'DONE' }) });
assert.equal(completeActionResponse.status, 200);
assert.equal((await completeActionResponse.json()).status, 'DONE');
const tinyPng = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=';
const jobResponse = await fetch(`${base}/api/jobs`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: auth }, body: JSON.stringify({ patientId: patient.id, imageDataUrl: tinyPng }) });
assert.equal(jobResponse.status, 202);
const createdJob = await jobResponse.json();
assert.equal(createdJob.status, 'REQUEST');
assert.equal(createdJob.evaluationType, '帳票判定中');
const parallelJobResponse = await fetch(`${base}/api/jobs`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: auth }, body: JSON.stringify({ patientId: patient.id, imageDataUrl: tinyPng }) });
assert.equal(parallelJobResponse.status, 202);
const parallelJob = await parallelJobResponse.json();
assert.notEqual(parallelJob.id, createdJob.id);
const runningJobs = await fetch(`${base}/api/jobs`, { headers: { Authorization: auth } }).then(r => r.json());
assert.ok(runningJobs.some(job => job.id === createdJob.id));
assert.ok(runningJobs.some(job => job.id === parallelJob.id));
let finishedJob, finishedParallelJob;
for (let attempt = 0; attempt < 30; attempt += 1) {
  await new Promise(resolve => setTimeout(resolve, 25));
  [finishedJob, finishedParallelJob] = await Promise.all([
    fetch(`${base}/api/jobs/${createdJob.id}`, { headers: { Authorization: auth } }).then(r => r.json()),
    fetch(`${base}/api/jobs/${parallelJob.id}`, { headers: { Authorization: auth } }).then(r => r.json())
  ]);
  if (finishedJob.status === 'ERROR' && finishedParallelJob.status === 'ERROR') break;
}
assert.equal(finishedJob.status, 'ERROR');
assert.equal(finishedParallelJob.status, 'ERROR');
assert.match(finishedJob.error, /OPENAI_API_KEY/);
const patientImportPreviewResponse = await fetch(`${base}/api/integration/patients/import`, { method: 'POST', headers: { Authorization: auth, 'Content-Type': 'application/json' }, body: JSON.stringify({ rows: [{ facilityPatientId: patient.facilityPatientId, name: '別人候補', birthDate: patient.birthDate }, { facilityPatientId: 'CSVNEW001', name: 'CSV新規患者', birthDate: '1950-01-02' }] }) });
assert.equal(patientImportPreviewResponse.status, 200);
const patientImportPreview = await patientImportPreviewResponse.json();
assert.equal(patientImportPreview.mode, 'PREVIEW');
assert.equal(patientImportPreview.counts.CONFLICT, 1);
assert.equal(patientImportPreview.counts.CREATE, 1);
const patientImportBlockedResponse = await fetch(`${base}/api/integration/patients/import`, { method: 'POST', headers: { Authorization: auth, 'Content-Type': 'application/json' }, body: JSON.stringify({ apply: true, rows: [{ facilityPatientId: patient.facilityPatientId, name: '別人候補', birthDate: patient.birthDate }, { facilityPatientId: 'CSVNEW001', name: 'CSV新規患者', birthDate: '1950-01-02' }] }) });
assert.equal(patientImportBlockedResponse.status, 409);
assert.equal((await patientImportBlockedResponse.json()).created, 0);
const patientImportApplyResponse = await fetch(`${base}/api/integration/patients/import`, { method: 'POST', headers: { Authorization: auth, 'Content-Type': 'application/json' }, body: JSON.stringify({ apply: true, rows: [{ facilityPatientId: 'CSVNEW001', name: 'CSV新規患者', birthDate: '1950-01-02' }] }) });
assert.equal(patientImportApplyResponse.status, 200);
assert.equal((await patientImportApplyResponse.json()).created, 1);
const clinicalRows = [{ facilityPatientId: 'CSVNEW001', wardName: '回復期B病棟', diseaseCategory: '脳血管疾患', admissionDate: '2026-08-01', plannedDischargeDate: '2026-10-01', dischargeDate: '', limitDays: '150' }];
const clinicalPreviewResponse = await fetch(`${base}/api/integration/clinical/import`, { method: 'POST', headers: { Authorization: auth, 'Content-Type': 'application/json' }, body: JSON.stringify({ rows: clinicalRows }) });
assert.equal(clinicalPreviewResponse.status, 200);
assert.equal((await clinicalPreviewResponse.json()).counts.CREATE, 1);
const clinicalApplyResponse = await fetch(`${base}/api/integration/clinical/import`, { method: 'POST', headers: { Authorization: auth, 'Content-Type': 'application/json' }, body: JSON.stringify({ apply: true, rows: clinicalRows }) });
assert.equal(clinicalApplyResponse.status, 200);
assert.equal((await clinicalApplyResponse.json()).created, 1);
const clinicalConflictResponse = await fetch(`${base}/api/integration/clinical/import`, { method: 'POST', headers: { Authorization: auth, 'Content-Type': 'application/json' }, body: JSON.stringify({ apply: true, rows: [{ ...clinicalRows[0], wardName: '別病棟' }] }) });
assert.equal(clinicalConflictResponse.status, 409);
assert.equal((await clinicalConflictResponse.json()).created, 0);
const rehabIntegrationRows = [{ externalRecordId: 'EXT-REHAB-001', facilityPatientId: 'CSVNEW001', recordedAt: '2026-08-10T09:00', therapistName: 'CSV療法士', intervention: '歩行練習', durationMinutes: '40', outcome: '見守りで実施' }];
const rehabIntegrationPreview = await fetch(`${base}/api/integration/rehab-records/import`, { method: 'POST', headers: { Authorization: auth, 'Content-Type': 'application/json' }, body: JSON.stringify({ rows: rehabIntegrationRows }) }).then(response => response.json());
assert.equal(rehabIntegrationPreview.counts.CREATE, 1);
const rehabIntegrationApplyResponse = await fetch(`${base}/api/integration/rehab-records/import`, { method: 'POST', headers: { Authorization: auth, 'Content-Type': 'application/json' }, body: JSON.stringify({ apply: true, rows: rehabIntegrationRows }) });
assert.equal(rehabIntegrationApplyResponse.status, 200);
assert.equal((await rehabIntegrationApplyResponse.json()).created, 1);
const rehabIntegrationDuplicate = await fetch(`${base}/api/integration/rehab-records/import`, { method: 'POST', headers: { Authorization: auth, 'Content-Type': 'application/json' }, body: JSON.stringify({ rows: rehabIntegrationRows }) }).then(response => response.json());
assert.equal(rehabIntegrationDuplicate.counts.UNCHANGED, 1);
const clinicalEventRows = [{ externalEventId: 'EXT-LAB-001', facilityPatientId: 'CSVNEW001', eventType: 'LAB', occurredAt: '2026-08-11T08:30', title: 'CRP', value: '0.4', unit: 'mg/dL', note: '院内検査' }];
const clinicalEventPreview = await fetch(`${base}/api/integration/clinical-events/import`, { method: 'POST', headers: { Authorization: auth, 'Content-Type': 'application/json' }, body: JSON.stringify({ rows: clinicalEventRows }) }).then(response => response.json());
assert.equal(clinicalEventPreview.counts.CREATE, 1);
assert.match(clinicalEventPreview.usageNote, /医療者確認/);
const clinicalEventApplyResponse = await fetch(`${base}/api/integration/clinical-events/import`, { method: 'POST', headers: { Authorization: auth, 'Content-Type': 'application/json' }, body: JSON.stringify({ apply: true, rows: clinicalEventRows }) });
assert.equal(clinicalEventApplyResponse.status, 200);
assert.equal((await clinicalEventApplyResponse.json()).created, 1);
const clinicalEventDuplicate = await fetch(`${base}/api/integration/clinical-events/import`, { method: 'POST', headers: { Authorization: auth, 'Content-Type': 'application/json' }, body: JSON.stringify({ rows: clinicalEventRows }) }).then(response => response.json());
assert.equal(clinicalEventDuplicate.counts.UNCHANGED, 1);
const importedClinicalEvents = await fetch(`${base}/api/clinical-events`, { headers: { Authorization: auth } }).then(response => response.json());
assert.equal(importedClinicalEvents.some(item => item.externalEventId === 'EXT-LAB-001' && item.eventType === 'LAB'), true);
const integrationRuns = await fetch(`${base}/api/integration/patient-runs`, { headers: { Authorization: auth } }).then(response => response.json());
assert.equal(integrationRuns.length >= 12, true);
assert.equal(integrationRuns.some(run => run.status === 'BLOCKED'), true);
assert.equal(integrationRuns.some(run => run.type === 'CLINICAL_CSV'), true);
assert.equal(integrationRuns.some(run => run.type === 'REHAB_RECORD_CSV'), true);
assert.equal(integrationRuns.some(run => run.type === 'CLINICAL_EVENT_CSV'), true);
const integrationCoverageResponse = await fetch(`${base}/api/integration/coverage`, { headers: { Authorization: auth } });
assert.equal(integrationCoverageResponse.status, 200);
const integrationCoverage = await integrationCoverageResponse.json();
assert.equal(integrationCoverage.patientCount, 5);
assert.equal(integrationCoverage.quality.duplicatesPrevented >= 2, true);
assert.equal(integrationCoverage.quality.errorsDetected >= 2, true);
assert.match(integrationCoverage.note, /実証導入前後の時間測定/);
for (const measurement of [
  { phase: 'BASELINE', workflow: 'PLAN', measuredAt: '2026-08-01', minutes: 120, cases: 4, staffRole: 'PT' },
  { phase: 'TRIAL', workflow: 'PLAN', measuredAt: '2026-08-08', minutes: 60, cases: 4, staffRole: 'PT' },
]) {
  const response = await fetch(`${base}/api/pilot/time-measurements`, { method: 'POST', headers: { Authorization: auth, 'Content-Type': 'application/json' }, body: JSON.stringify(measurement) });
  assert.equal(response.status, 201);
}
const pilotTimeSummaryResponse = await fetch(`${base}/api/pilot/time-summary`, { headers: { Authorization: auth } });
assert.equal(pilotTimeSummaryResponse.status, 200);
const pilotTimeSummary = await pilotTimeSummaryResponse.json();
const planTimeSummary = pilotTimeSummary.workflows.find(item => item.workflow === 'PLAN');
assert.equal(planTimeSummary.baselineAverage, 30);
assert.equal(planTimeSummary.trialAverage, 15);
assert.equal(planTimeSummary.reductionRate, 50);
assert.equal(planTimeSummary.status, 'TARGET_MET');
assert.match(pilotTimeSummary.note, /条件差/);
const safetyEventResponse = await fetch(`${base}/api/pilot/safety-events`, { method: 'POST', headers: { Authorization: auth, 'Content-Type': 'application/json' }, body: JSON.stringify({ category: 'NEAR_MISS', severity: 'LOW', occurredAt: '2026-08-09', description: '患者選択を確定前に再確認した', immediateAction: '確認手順を実施' }) });
assert.equal(safetyEventResponse.status, 201);
const safetyEvent = await safetyEventResponse.json();
let safetySummary = await fetch(`${base}/api/pilot/safety-summary`, { headers: { Authorization: auth } }).then(response => response.json());
assert.equal(safetySummary.counts.nearMiss, 1);
assert.equal(safetySummary.counts.serious, 0);
assert.equal(safetySummary.gate.status, 'MET');
const safetyResolveResponse = await fetch(`${base}/api/pilot/safety-events/${safetyEvent.id}`, { method: 'PUT', headers: { Authorization: auth, 'Content-Type': 'application/json' }, body: JSON.stringify({ status: 'RESOLVED', resolution: '患者ID二点照合を手順に追加' }) });
assert.equal(safetyResolveResponse.status, 200);
safetySummary = await fetch(`${base}/api/pilot/safety-summary`, { headers: { Authorization: auth } }).then(response => response.json());
assert.equal(safetySummary.counts.open, 0);
assert.match(safetySummary.note, /試行を停止/);
for (const staffRole of ['PT','OT','看護']) {
  const feedbackResponse = await fetch(`${base}/api/pilot/staff-feedback`, { method: 'POST', headers: { Authorization: auth, 'Content-Type': 'application/json' }, body: JSON.stringify({ staffRole, continueUse: 'YES', usability: 4, usefulness: 5, burden: 2, comment: '患者一覧の絞り込みを改善してほしい' }) });
  assert.equal(feedbackResponse.status, 201);
}
const feedbackSummaryResponse = await fetch(`${base}/api/pilot/staff-feedback-summary`, { headers: { Authorization: auth } });
assert.equal(feedbackSummaryResponse.status, 200);
const feedbackSummary = await feedbackSummaryResponse.json();
assert.equal(feedbackSummary.responses, 3);
assert.equal(feedbackSummary.agreementRate, 100);
assert.equal(feedbackSummary.averages.usability, 4);
assert.equal(feedbackSummary.averages.usefulness, 5);
assert.equal(feedbackSummary.averages.burden, 2);
assert.equal(feedbackSummary.gate.status, 'MET');
assert.equal(feedbackSummary.roles.length, 3);
const invalidStudyResponse = await fetch(`${base}/api/pilot/study`, { method: 'PUT', headers: { Authorization: auth, 'Content-Type': 'application/json' }, body: JSON.stringify({ wardName: '回復期病棟', owner: '責任者', patientLimit: 10, baselineStart: '2026-08-10', baselineEnd: '2026-08-20', trialStart: '2026-08-15', trialEnd: '2026-09-15' }) });
assert.equal(invalidStudyResponse.status, 400);
const studyResponse = await fetch(`${base}/api/pilot/study`, { method: 'PUT', headers: { Authorization: auth, 'Content-Type': 'application/json' }, body: JSON.stringify({ wardName: '回復期病棟A', owner: '実証責任者', patientLimit: 10, baselineStart: '2026-07-01', baselineEnd: '2026-07-14', trialStart: '2026-07-21', trialEnd: '2026-08-21', note: '限定患者で実施' }) });
assert.equal(studyResponse.status, 201);
const studyStatusResponse = await fetch(`${base}/api/pilot/study`, { headers: { Authorization: auth } });
assert.equal(studyStatusResponse.status, 200);
const studyStatus = await studyStatusResponse.json();
assert.equal(studyStatus.study.wardName, '回復期病棟A');
assert.equal(studyStatus.study.patientLimit, 10);
assert.equal(studyStatus.phase, 'TRIAL');
assert.equal(studyStatus.progress > 0, true);
let approvalSummary = await fetch(`${base}/api/pilot/approvals`, { headers: { Authorization: auth } }).then(response => response.json());
assert.equal(approvalSummary.summary.status, 'PENDING');
for (const [role, approverName] of [['HOSPITAL_DIRECTOR','病院責任者'],['INFORMATION_SECURITY','情報管理責任者'],['CLINICAL_REPRESENTATIVE','現場代表']]) {
  const approvalResponse = await fetch(`${base}/api/pilot/approvals`, { method: 'POST', headers: { Authorization: auth, 'Content-Type': 'application/json' }, body: JSON.stringify({ role, decision: 'APPROVE', approverName, comment: '条件を確認済み' }) });
  assert.equal(approvalResponse.status, 201);
}
approvalSummary = await fetch(`${base}/api/pilot/approvals`, { headers: { Authorization: auth } }).then(response => response.json());
assert.equal(approvalSummary.summary.status, 'APPROVED');
assert.equal(approvalSummary.summary.approved, 3);
assert.equal(approvalSummary.history.length, 3);
assert.match(approvalSummary.note, /三者すべて/);
let expansionSummary = await fetch(`${base}/api/pilot/expansions`, { headers: { Authorization: auth } }).then(response => response.json());
assert.equal(expansionSummary.eligible, true);
const expansionResponse = await fetch(`${base}/api/pilot/expansions`, { method: 'POST', headers: { Authorization: auth, 'Content-Type': 'application/json' }, body: JSON.stringify({ wardName: '回復期病棟B', owner: '拡大責任者', startDate: '2026-09-01', patientLimit: 30, monitoringDays: 28, note: '安全事象を継続監視' }) });
assert.equal(expansionResponse.status, 201);
expansionSummary = await fetch(`${base}/api/pilot/expansions`, { headers: { Authorization: auth } }).then(response => response.json());
assert.equal(expansionSummary.expansions.length, 1);
assert.equal(expansionSummary.expansions[0].wardName, '回復期病棟B');
assert.equal(expansionSummary.expansions[0].monitoringDays, 28);
assert.match(expansionSummary.note, /重点監視期間/);
const readinessResponse = await fetch(`${base}/api/pilot/readiness`, { headers: { Authorization: auth } });
assert.equal(readinessResponse.status, 200);
const readiness = await readinessResponse.json();
assert.equal(readiness.status, 'READY');
assert.equal(readiness.gates.find(item => item.key === 'TIME').status, 'MET');
assert.equal(readiness.gates.find(item => item.key === 'SAFETY').status, 'MET');
assert.equal(readiness.gates.find(item => item.key === 'AGREEMENT').status, 'MET');
assert.match(readiness.limitations, /正式な導入承認を代替しません/);
const pilotReportResponse = await fetch(`${base}/api/pilot/report.html`, { headers: { Authorization: auth } });
assert.equal(pilotReportResponse.status, 200);
assert.match(pilotReportResponse.headers.get('content-type'), /text\/html/);
const pilotReport = await pilotReportResponse.text();
assert.match(pilotReport, /西大和モデル 実証導入結果報告/);
assert.match(pilotReport, /総合判定：<strong>本導入候補<\/strong>/);
assert.match(pilotReport, /患者名・患者IDを含まない/);
assert.match(pilotReport, /病院責任者/);
const removedAuditEndpoint = await fetch(`${base}/api/audit`, { headers: { Authorization: auth } });
assert.equal(removedAuditEndpoint.status, 404);
const databaseBytes = await readFile(path.join(temp, 'database.json'));
assert.equal(databaseBytes.subarray(0, 6).toString(), 'AIOCR1');
assert.equal(databaseBytes.includes(Buffer.from('テスト患者')), false);
const imageBytes = await readFile(path.join(temp, 'images', createdJob.imageFile));
assert.equal(imageBytes.subarray(0, 6).toString(), 'AIOCR1');
const backupResponse = await fetch(`${base}/api/admin/backup`, { method: 'POST', headers: { Authorization: auth, 'Content-Type': 'application/json' }, body: '{}' });
assert.equal(backupResponse.status, 201);
const backup = await backupResponse.json();
assert.match(backup.backup, /^backup-/);
const backupManifest = JSON.parse(await readFile(path.join(temp, 'backups', backup.backup, 'manifest.json'), 'utf8'));
assert.equal(backupManifest.encrypted, true);
const backupStatusResponse = await fetch(`${base}/api/admin/backup-status`, { headers: { Authorization: auth } });
assert.equal(backupStatusResponse.status, 200);
const backupStatus = await backupStatusResponse.json();
assert.equal(backupStatus.count >= 1, true);
assert.equal(backupStatus.latest.encrypted, true);
assert.match(backupStatus.restorePolicy, /画面からの自動復元は行いません/);
const deleteHistoryResponse = await fetch(`${base}/api/jobs`, { method: 'DELETE', headers: { Authorization: auth, 'Content-Type': 'application/json' }, body: '{}' });
assert.equal(deleteHistoryResponse.status, 200);
const deleteHistoryResult = await deleteHistoryResponse.json();
assert.equal(deleteHistoryResult.deletedCount, 2);
const jobsAfterDelete = await fetch(`${base}/api/jobs`, { headers: { Authorization: auth } }).then(r => r.json());
assert.equal(jobsAfterDelete.length, 0);
await new Promise(resolve => server.close(resolve));
await rm(temp, { recursive: true, force: true });
console.log('standalone smoke test: OK');
